apiVersion: v1
kind: Service
metadata:
  annotations:
    fabric8.io/expose: "true"
    fabric8.io/exposeUrl: http://cdf-conference-site.jx-staging.34.83.214.92.nip.io
    fabric8.io/ingress.annotations: 'kubernetes.io/ingress.class: nginx'
    jenkins.io/chart: env
  labels:
    chart: cdf-conference-site-0.0.1
    jenkins.io/chart-release: jx
    jenkins.io/namespace: jx-staging
    jenkins.io/version: "32"
  name: cdf-conference-site
  namespace: jx-staging
  selfLink: /api/v1/namespaces/jx-staging/services/cdf-conference-site
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: jx-cdf-conference-site
  sessionAffinity: None
  type: ClusterIP

