apiVersion: apiextensions.k8s.io/v1beta1 
kind: CustomResourceDefinition
metadata:
  name: conferences.alpha.k8s.salaboy.com
spec:
  group: alpha.k8s.salaboy.com
  version: v1 
  scope: Cluster
  names:
    plural: conferences
    singular: conference
    kind: Conference
    shortNames:
    - conf
  additionalPrinterColumns:
    - name: LOCATION
      type: string
      description: Location of the Conference
      JSONPath: .spec.location
    - name: YEAR
      type: string
      description: The Year of the Conference
      JSONPath: .spec.year
    - name: STATUS
      type: string
      description: The Status of the Conference
      JSONPath: .spec.status
    - name: URL
      type: string
      description: The URL of the Conference
      JSONPath: .spec.url    