apiVersion: apiextensions.k8s.io/v1beta1 
kind: CustomResourceDefinition
metadata:
  name: conferences.alpha.k8s.salaboy.com
spec:
  group: alpha.k8s.salaboy.com
  version: v1 
  scope: Cluster
  names:
    plural: conferences
    singular: conference
    kind: Conference
    shortNames:
    - conf
  additionalPrinterColumns:
    - name: STATUS
      type: string
      description: The Status of the App
      JSONPath: .spec.status
    - name: URL
      type: string
      description: The URL of the App
      JSONPath: .spec.url    